name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4

      - name: Lint
        run: uv run ruff check src tests

      - name: Compile
        run: uv run python -m compileall -q src tests

      - name: Run tests
        run: uv run pytest --cov=src/paperflow --cov-report=term-missing
